export const WATTSWAP_ABI = {
  address: "0xf33b711e1e5a23f85c06beeb55800b6d7b7dbafccab1de28b3992f317427cdff",
  name: "wattswap",
  friends: [],
  exposed_functions: [
    {
      name: "confirm",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [],
    },
    {
      name: "create_swap",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "u64"],
      return: [],
    },
    {
      name: "get_active_swaps",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<0xf33b711e1e5a23f85c06beeb55800b6d7b7dbafccab1de28b3992f317427cdff::wattswap::WattSwap>"],
    },
    {
      name: "get_swap_details",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "u64"],
      return: ["u64", "address", "address", "u64", "u64", "bool"],
    },
    {
      name: "get_swaps",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<0xf33b711e1e5a23f85c06beeb55800b6d7b7dbafccab1de28b3992f317427cdff::wattswap::WattSwap>"],
    },
    {
      name: "initialize_swaps",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "purchase",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "u64"],
      return: [],
    },
  ],
  structs: [
    {
      name: "ConfirmEvent",
      is_native: false,
      is_event: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "seller", type: "address" },
        { name: "swap_id", type: "u64" },
      ],
    },
    {
      name: "PurchaseEvent",
      is_native: false,
      is_event: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "buyer", type: "address" },
        { name: "seller", type: "address" },
        { name: "swap_id", type: "u64" },
        { name: "apt_amount", type: "u64" },
      ],
    },
    {
      name: "SwapCreatedEvent",
      is_native: false,
      is_event: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "seller", type: "address" },
        { name: "swap_id", type: "u64" },
        { name: "watt_amount", type: "u64" },
        { name: "apt_price", type: "u64" },
      ],
    },
    {
      name: "WattSwap",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store", "key"],
      generic_type_params: [],
      fields: [
        { name: "id", type: "u64" },
        { name: "seller", type: "address" },
        { name: "buyer", type: "address" },
        { name: "watt_amount", type: "u64" },
        { name: "apt_price", type: "u64" },
        { name: "is_active", type: "bool" },
      ],
    },
    {
      name: "WattSwapEvents",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "swap_created_events",
          type: "0x1::event::EventHandle<0xf33b711e1e5a23f85c06beeb55800b6d7b7dbafccab1de28b3992f317427cdff::wattswap::SwapCreatedEvent>",
        },
        {
          name: "purchase_events",
          type: "0x1::event::EventHandle<0xf33b711e1e5a23f85c06beeb55800b6d7b7dbafccab1de28b3992f317427cdff::wattswap::PurchaseEvent>",
        },
        {
          name: "confirm_events",
          type: "0x1::event::EventHandle<0xf33b711e1e5a23f85c06beeb55800b6d7b7dbafccab1de28b3992f317427cdff::wattswap::ConfirmEvent>",
        },
      ],
    },
    {
      name: "WattSwaps",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "swaps",
          type: "vector<0xf33b711e1e5a23f85c06beeb55800b6d7b7dbafccab1de28b3992f317427cdff::wattswap::WattSwap>",
        },
        { name: "swap_count", type: "u64" },
      ],
    },
  ],
} as const;
